### ISSUE TITLE
PHP 7.2 - PHP Module

### ISSUE THREAD

**Issue by ShockFromBL** [BlocklandGlass/GlassWebsite#44]
/public/addons/upload/upload.php

```
Fatal error:
  Uncaught ErrorException: Bad Require in /var/www/glass/private/autoload.php:7
Stack trace:
  #0 [internal function]: {closure}('ZipArchive')
  #1 /var/www/glass/private/class/AddonFileHandler.php(28): spl_autoload_call('ZipArchive')
  #2 /var/www/glass/private/class/UploadManager.php(125): Glass\AddonFileHandler::validateAddon('/var/www/glass/...')
  #3 /var/www/glass/public/addons/upload/upload.php(6): Glass\UploadManager::getStatus(Array, Array)
  #4 /var/www/glass/public/addons/upload/upload.debug.php(5): include('/var/www/glass/...')
  #5 {main} thrown in /var/www/glass/private/autoload.php on line 7
```

**Comment by dpendic** [comment]
Updated php7.0-zip and php7.0-curl to php7.2-zip and php7.2-curl respectively.
